# Generated by Django 5.0.1 on 2024-03-08 15:55

from django.db import migrations

def all_can_vote(apps, schema_editor):
    Account = apps.get_model('users', 'Account')
    for user in Account.objects.all():
        user.can_vote = True
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_can_vote'),
    ]

    operations = [
        migrations.RunPython(all_can_vote),
    ]
