# Generated by Django 5.0.1 on 2024-03-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240308_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='can_vote',
            field=models.BooleanField(default=True, verbose_name='Может голосовать?'),
        ),
    ]
