# Generated by Django 5.0.1 on 2024-02-09 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер раунда')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема')),
                ('shown', models.BooleanField(default=False, verbose_name='Показан?')),
            ],
        ),
        migrations.CreateModel(
            name='VoteCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vote_cards', verbose_name='Карта')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('boost', models.IntegerField(verbose_name='Бонус')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.stage', verbose_name='Раунд')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistakes', models.IntegerField(verbose_name='Ошибки')),
                ('design', models.IntegerField(verbose_name='Дизайн')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
                ('realisation', models.IntegerField(verbose_name='Реализация')),
                ('idea', models.IntegerField(verbose_name='Идея')),
                ('comment', models.TextField()),
                ('result', models.IntegerField(blank=True, null=True, verbose_name='Итог')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vote.votecard')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
    ]
