# Generated by Django 5.0.1 on 2024-02-09 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Раунд', 'verbose_name_plural': 'Раунды'},
        ),
        migrations.AlterField(
            model_name='vote',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vote.votecard'),
        ),
    ]
