# Generated by Django 5.0.1 on 2024-02-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_votecard_boost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='votecard',
            name='boost',
            field=models.IntegerField(default=0, verbose_name='Бонус'),
        ),
    ]
