# Generated by Django 5.0.1 on 2024-02-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vote', '0004_alter_vote_comment_alter_votecard_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='votecard',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VoteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vote_tokens')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens',
                                           to='vote.votecard')),
            ],
        ),
    ]
