# Generated by Django 5.0.1 on 2024-02-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vote', '0005_votecard_comment_votetoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votetoken',
            options={'verbose_name': 'Токен', 'verbose_name_plural': 'Токены'},
        ),
        migrations.AlterField(
            model_name='votecard',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
