# Generated by Django 5.0.1 on 2024-03-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_votetoken_options_alter_votecard_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='mistakes',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='realisation',
        ),
        migrations.AddField(
            model_name='vote',
            name='in_game',
            field=models.IntegerField(default=1, verbose_name='Видение в игре'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='theme_like',
            field=models.IntegerField(default=1, verbose_name='Соответствие теме'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='design',
            field=models.IntegerField(verbose_name='Внешний вид'),
        ),
    ]
