# Generated by Django 5.0.1 on 2024-03-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_cl_alter_card_image_alter_card_mana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='plain_text',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Очищенный текст'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Текст'),
        ),
    ]
